apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-express-nodejs-demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-nodejs-demo-backend
  template:
    metadata:
      labels:
        app: express-nodejs-demo-backend
    spec:
      containers:
      - name: express-nodejs-demo-backend
        image: docker.io/azxcvba81/henry_dev_nodejs_demo_express:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Exists"
        effect: "NoSchedule"